
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://spring-service.c7e2e4mw2c3e.ap-northeast-2.rds.amazonaws.com:3306/spring_service
    username: admin
    password: asdf794613
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate: # hibernate 사용 설정
      # 애플리케이션 실행 시점에 테이블을 다 지우고, 내가 가진 entity 정보를 보고 다시 테이블 자동 생성
      # if exists drop table 해주고 다시 만들어준다고 보면 된다.
      ddl-auto: create
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug